#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Mock Bulletin Generator — Windows Local Preview Tool
=====================================================
PURPOSE:
    Mimics the final PDF layout produced by RunSARBulletinCreationV2.sh on the Linux
    server, but runs entirely on Windows using Python + ReportLab.
    Use this ONLY for local verification. The actual production PDF is generated
    by the GMT Bash pipeline on the INCOIS Linux server.

STRUCTURE:
    Page 1  — INCOIS header + V2-style static summary map (finalconvexhull image, 
               i.e. the original GMT hull-polygon image from the V2 pipeline).
    Page 2+ — Paginated time-evolution probability maps (2x2 grid per page)
               generated by sarat_visuals.plot_combined().

USAGE:
    Run from the SARAT root folder:
        python mock_bulletin_generator.py [case_id]
    Default case_id = 6687
"""

import os
import sys
import glob
from datetime import datetime

from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Image, Paragraph, Spacer, PageBreak, HRFlowable
)
from reportlab.lib import colors


# ─────────────────────────────────────────────────────────────
# Helper: build the standard INCOIS header block
# ─────────────────────────────────────────────────────────────
def _incois_header(styles):
    """Returns a list of ReportLab flowables that mimic the GMT header."""
    title_style = ParagraphStyle(
        'TitleBlue', parent=styles['Heading1'],
        fontSize=20, textColor=colors.blue,
        alignment=TA_CENTER, fontName='Helvetica-Bold', spaceAfter=2
    )
    sub1 = ParagraphStyle(
        'Sub1', parent=styles['Normal'],
        fontSize=14, alignment=TA_CENTER,
        fontName='Helvetica-Bold', spaceAfter=2
    )
    sub2 = ParagraphStyle(
        'Sub2', parent=styles['Normal'],
        fontSize=10, alignment=TA_CENTER,
        fontName='Helvetica-Bold', spaceAfter=2
    )
    sub3 = ParagraphStyle(
        'Sub3', parent=styles['Normal'],
        fontSize=10, alignment=TA_CENTER,
        fontName='Helvetica', spaceAfter=6
    )
    return [
        Paragraph("SARAT", title_style),
        Paragraph("Search And Rescue Aid Tool", sub1),
        Paragraph("ESSO-INDIAN NATIONAL CENTRE FOR OCEAN INFORMATION SERVICES", sub2),
        Paragraph("(Ministry of Earth Sciences, Government of India)", sub3),
        Paragraph("ISO 9001 : 2008 Certified  Ocean State Forecast Services", sub3),
        HRFlowable(width="100%", thickness=1, color=colors.grey, spaceAfter=6),
    ]


# ─────────────────────────────────────────────────────────────
# Helper: LKP + advisory text block (mirrors GMT pstext lines)
# ─────────────────────────────────────────────────────────────
def _lkp_block(styles, lon_dd, lat_dd):
    """Returns LKP and advisory text flowables including decimal degrees."""

    def _dd_to_dms(dd):
        deg = int(dd)
        minutes_full = (dd - deg) * 60
        mins = int(minutes_full)
        secs = int((minutes_full - mins) * 60)
        return deg, mins, secs

    lo_d, lo_m, lo_s = _dd_to_dms(lon_dd)
    lt_d, lt_m, lt_s = _dd_to_dms(lat_dd)

    lkp_style = ParagraphStyle(
        'LKP', parent=styles['Normal'],
        fontSize=10, alignment=TA_LEFT,
        fontName='Helvetica', textColor=colors.HexColor('#333333'),
        spaceBefore=4, spaceAfter=2
    )

    lkp_text = (
        f"Last Known Position is  "
        f"Longitude: {lo_d} deg {lo_m} mins {lo_s} secs ({lon_dd:.4f} deg),  "
        f"Latitude: {lt_d} deg {lt_m} mins {lt_s} secs ({lat_dd:.4f} deg)"
    )
    adv_text = (
        f"Advisory generated on: {datetime.now().strftime('%d/%m/%Y %H:%M')} hrs IST"
    )
    sim_text = "The model simulation has been done with 10 km Uncertainty in Initial Condition"

    return [
        Paragraph(sim_text,  lkp_style),
        Paragraph(lkp_text,  lkp_style),
        Paragraph(adv_text,  lkp_style),
        Spacer(1, 0.1 * inch),
    ]


# ─────────────────────────────────────────────────────────────
# Main generator
# ─────────────────────────────────────────────────────────────
def generate_mock_bulletin(case_id, figure_dir, lon_dd=69.833, lat_dd=22.580):
    """
    Build the mock bulletin PDF.

    Parameters
    ----------
    case_id   : str or int  — e.g. "6687"
    figure_dir: str         — path to case figure folder
    lon_dd    : float       — LKP longitude (decimal degrees)
    lat_dd    : float       — LKP latitude  (decimal degrees)
    """
    output_pdf = f"mock_bulletein_{case_id}.pdf"

    doc = SimpleDocTemplate(
        output_pdf,
        pagesize=landscape(A4),
        rightMargin=0.5 * inch,
        leftMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
    )

    styles = getSampleStyleSheet()
    section_style = ParagraphStyle(
        'Section', parent=styles['Heading2'],
        fontSize=13, textColor=colors.HexColor('#1a3c6e'),
        fontName='Helvetica-Bold', spaceBefore=8, spaceAfter=4
    )

    story = []

    # ── PAGE 1: Header + V2-style static hull/summary image ──────────────
    story += _incois_header(styles)
    story += _lkp_block(styles, lon_dd, lat_dd)

    # V2 static map — originally produced by GMT pscoast + psxy polygon loop
    # This is the original "region probability hull" image from the V2 pipeline.
    # On the Linux server this is drawn directly by GMT; here we embed the
    # pre-existing sarat_report PDF's first-page equivalent if available,
    # otherwise we show a placeholder notice.
    v2_candidates = [
        os.path.join(figure_dir, f"sarat_report_{case_id}_page1.png"),
        os.path.join(figure_dir, f"v2_map_{case_id}.png"),
        os.path.join(figure_dir, f"finalconvexhull_{case_id}.png"),
    ]
    v2_img = next((p for p in v2_candidates if os.path.exists(p)), None)

    story.append(Paragraph("V2 Search Region Summary Map (Hull-Polygon Style)", section_style))
    if v2_img:
        story.append(Image(v2_img, width=9.5 * inch, height=4.5 * inch))
    else:
        story.append(Paragraph(
            "<font color='#888888'>[V2 static hull map not available locally — "
            "this image is generated by GMT on the Linux server. "
            "On the server, the original pscoast / psxy polygon plot appears here.]</font>",
            styles['Normal']
        ))

    story.append(PageBreak())

    # ── PAGES 2+: Paginated 2x2 time-evolution maps ──────────────────────
    story.append(Paragraph("Time-Evolution Probability Maps", section_style))
    story += _lkp_block(styles, lon_dd, lat_dd)

    # Collect all combined page PNGs in order
    page_pngs = sorted(
        glob.glob(os.path.join(figure_dir, f"seeding_duration_{case_id}_combined_page_*.png"))
    )

    if page_pngs:
        for i, png_path in enumerate(page_pngs):
            story.append(Paragraph(
                f"Probability Maps — Page {i + 1} of {len(page_pngs)}",
                ParagraphStyle('PageLbl', parent=styles['Normal'],
                               fontSize=9, textColor=colors.grey, spaceAfter=4)
            ))
            story.append(Image(png_path, width=10.5 * inch, height=6.8 * inch))
            if i < len(page_pngs) - 1:
                story.append(PageBreak())
                story += _incois_header(styles)   # repeat header on each new page
    else:
        # Fallback: try the old single-combined image
        old_combined = os.path.join(figure_dir, f"seeding_duration_{case_id}_combined.png")
        if os.path.exists(old_combined):
            story.append(Image(old_combined, width=10.5 * inch, height=5.5 * inch))
        else:
            story.append(Paragraph(
                "<font color='red'>No combined probability images found! "
                "Run saratv3visuals.py first to generate them.</font>",
                styles['Normal']
            ))

    doc.build(story)
    print(f"\nMock Bulletin PDF generated: {output_pdf}")
    print(f"  V2 static map        : {'found' if v2_img else 'not available (placeholder used)'}")
    print(f"  Time-evolution pages : {len(page_pngs)}")


# ─────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────
if __name__ == "__main__":
    case = sys.argv[1] if len(sys.argv) > 1 else "6687"

    # Resolve the figure directory relative to this script
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    figure_dir  = os.path.join(script_dir,
                                "sarat_new_visualization_changes",
                                f"case{case}", "figure")

    if not os.path.isdir(figure_dir):
        print(f"ERROR: figure directory not found: {figure_dir}")
        print("Run saratv3visuals.py first to generate outputs.")
        sys.exit(1)

    generate_mock_bulletin(case, figure_dir)
